#!/usr/bin/env python

import numpy as np

a = np.array([[0.5, -1],[-1, 2]], dtype = np.float32)
b = a.copy()
b = b.flatten()

for i in range(len(b)):
    if i%2 == 0:
        b[i] = 0 

if __name__ == "__main__":
    print(a.shape)
    print(b)

